### ISSUE TITLE
`test_regressor.py` and `test_classifier.py` occasionally taking forever and segfaulting

### ISSUE THREAD

**Issue by zzril** [Safe-DS/Library#348]
### Describe the bug

`tests/safeds/ml/classical/regression/test_regressor.py` and `tests/safeds/ml/classical/regression/test_classifier.py` occasionally take very long. I usually just abort them after half a minute or so, then restart, which works fine most of the time.

When the test gets stuck and I don't abort manually, this happens after several minutes:
```
[...]
tests/safeds/ml/classical/regression/test_lasso_regression.py ....                                                                                                                                                               [ 82%]
tests/safeds/ml/classical/regression/test_random_forest.py ...                                                                                                                                                                   [ 82%]
tests/safeds/ml/classical/regression/test_regressor.py ...................................................................Fatal Python error: Aborted
```
It goes on to print stacktraces for all threads, dumps a list of all imported python modules, and ends with a segmentation fault message.

---

For the `test_regressor.py`, I have observed the segfault 3 times within 10 attempts.
For `test_classifier.py`, it's rarer. Here, I have observed the segfault only one time so far.

---

### To Reproduce

Run `pytest` a bunch of times. Don't abort when it seems to get stuck, but wait (even if it takes 5 minutes).  
You'll probably get the "hang up" behaviour within 10 tries or so.

#### Setup:
OS: Linux
IDE: PyCharm
Python version: 3.10.6, inside poetry, inside venv
Poetry version: 1.4.2
pytest version: 7.3.1

---

### Expected behavior

The tests should not get stuck. Check for possible endless loops or endless recursions.

If this cannot be prevented in any way, there should at least be a timeout / some way to gracefully end the test with somewhat useful error message.

**Comment by zzril** [comment]
Happened less often to me in the last week; still not sure what it's caused by.  
Possibly some sort of memory limit was hit, triggering the OOM killer.

**Comment by lars-reimann** [comment]
I could reproduce this:

![image](https://github.com/Safe-DS/Stdlib/assets/2501322/3f6c3c35-7ab2-46a1-a2fc-31fddb80bc1d)

**Comment by zzril** [comment]
Yes, it only happens when running `pytest` from the console.

Passing the test folder explicitely with `pytest tests` does work however.

**Comment by zzril** [comment]
I just got an "low memory" warning by PyCharm while running `pytest`. It suggested to increase the heap size to 2048 MB (was at 19XX).

That might be an indicator that memory consumption was indeed a problem.

**Comment by lars-reimann** [comment]
Cannot reproduce this anymore.
