### ISSUE TITLE
For `TableTransformer`s, add a method to return a mapping of newly-created columns to old columns and vice-versa

### ISSUE THREAD

**Issue by zzril** [Safe-DS/Library#387]
### Is your feature request related to a problem?

For some `Transformer`s, such as the `OneHotEncoder`, that can add/remove/replace columns, it would be helpful to know what old columns correspond to what new columns.

### Desired solution

* Think of a sensible data structure for this mapping.
* Create an method for the `TableTransformer` that returns this mapping.
* Implement it in the existing transformers.

**Comment by lars-reimann** [comment]
Now that #647 is done and #328 won't be worked on, there's not much need for this anymore.
