### ISSUE TITLE
Schema can not recognize columns of Types RealNumber? and Integer?

### ISSUE THREAD

**Issue by daniaHu** [Safe-DS/Library#391]
### Describe the bug

Due to using pd.DataFrames as input for _from_pandas_dataframe in `src/safeds/data/tabular/typing/_schema.py`, columns with numerical values combined with missing values are automatically interpreted as columns of type RealNumber.

### To Reproduce

1. Find another data structure than DataFrame, that doesn't have that problem, and use it to create schema.  `src/safeds/data/tabular/typing/_schema.py`
2. Change tests in `tests/safeds/data/tabular/typing/test_schema.py` accordingly.

### Expected behavior

Expected is that "test_should_create_schema_from_pandas_dataframe" in `tests/safeds/data/tabular/typing/test_schema.py` 
-would return schema: {"A" : Integer?} by column with integers and None,
-and schema: {"A" : RealNumber?}  by column with RealNumbers and None

**Comment by lars-reimann** [comment]
The schema no longer contains information about missing values.
