### ISSUE TITLE
New column type(wontfix)

### ISSUE THREAD

**Issue by Gerhardsa0** [Safe-DS/Library#484]
### Is your feature request related to a problem?

I want to take multiple data points in a single row of a column. Right now it is not possible, because we do not support list or something similar in a column.

### Desired solution

Add a window column type

### Additional Context (optional)

This is in context to the #481 issue, because a time series consist of windows.

**Comment by lars-reimann** [comment]
@Gerhardsa0 Is this something you actually completed or that is no longer planned? In the latter case, please add an appropriate label (_duplicate_/_wontfix_) and close the issue as _not planned_ instead of _completed_.
