### ISSUE TITLE
Unable to install Triton

### ISSUE THREAD

**Issue by Gerhardsa0** [Safe-DS/Library#509]
### Describe the bug

When I try to merge my pr #508 it does not install the Triton package for Python 3.12, and I don't know really why.

https://github.com/openai/triton/issues/2707

![grafik](https://github.com/Safe-DS/Library/assets/113539440/1afba402-eef5-49dd-b059-b458c84baa12)

### To Reproduce

Try to ``` poetry add Triton```on Python 3.12

### Expected behavior

It should just install Triton, so it runs the test.

**Comment by lars-reimann** [comment]
What do you need it for?
