### ISSUE TITLE
feat: Add lag-plot for time series

### ISSUE THREAD

**Issue by Gerhardsa0** [Safe-DS/Library#519]
### Is your feature request related to a problem?

When working with time series, a lag plot is useful to see correlation between values and time. 
So when implementing this issue, the "lagging" itself must be implemented and the visualization.

### Desired solution

The user should call something like this:  ```ts.plot_lagplot()```

**Comment by lars-reimann** [comment]
Other plotting functions use the prefix `plot_`, so something like `plot_lagplot` would be appropriate. The first `plot` is a verb, while `lagplot` is the name of the plot.
