### ISSUE TITLE
feat: Add moving average plot 

### ISSUE THREAD

**Issue by Gerhardsa0** [Safe-DS/Library#521]
### Is your feature request related to a problem?

The user should be able to see the moving average in context with the time series.

### Desired solution

The user should just call something like this: ```ts.plot_movingaverage()```
When implementing this, the pandas ```df.roll```-function could be pretty useful.

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rolling.html

**Comment by Gerhardsa0** [comment]
@lars-reimann 
for the implementation I could use this function: https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.rolling_mean.html

But it's considered **unstable**, so should I use this function, or write an own rolling average?

**Comment by lars-reimann** [comment]
Use the polars version. If they change it, we change the implementation of our wrapper.

**Comment by Gerhardsa0** [comment]
Should there also be an moving average function for a Column, which calculates the moving average and returns it as a column.
The same goes for windows.

**Comment by lars-reimann** [comment]
Maybe later, you don't have to worry about that.
