### ISSUE TITLE
bug: Schema Types and Pandas dtypes are not always equal

### ISSUE THREAD

**Issue by Gerhardsa0** [Safe-DS/Library#576]
### Describe the bug

I was working on split rows and my test always failed, despite in safe-ds they had the exact same content. After a while I found that, the Column dtypes on empty columns are not getting overwritten. This is because we use the schema dtypes to overwrite the empty column types.

### To Reproduce

1. ```table = Table({"col1": [1]})```
2. ```t1, t2 = table.split_rows(1)```
3. ```print(t2.get_column_type("col1"))```
4. ```print(t2.get_column("col1")._data)```

Output:
Nothing?
Series([], Name: col1, dtype: int64)

### Expected behavior

I would expect the same data types in safe-ds and the internal handle in pandas.

### Additional Context (optional)

I fixed that in the ```TimeSeries```-class by manually overriting the pandas dtype on empty Columns to Object.

**Comment by lars-reimann** [comment]
This is fixed since we no longer compute types ourselves but rely on the inference of polars.
