### ISSUE TITLE
Add a new ImageDataset Class

### ISSUE THREAD

**Issue by Marsmaennchen221** [Safe-DS/Library#579]
### Is your feature request related to a problem?

This ImageDataset should handle an input as an ImageList and an output as either an ImageList a column that will be one hot encoded internally or a numerical table with values between 0 and 1. If the output is a table it should have the same amount of columns as the nn module has output neurons and all columns should have values between 0 and 1. If the output is a column the amount of one hot encoded values should not exceed the amount of output neurons of the nn module.

### Desired solution

Add a new ImageDataset Class
This class should also deliver batching methods for NN models

**Comment by lars-reimann** [comment]
Should the output not be a table instead of a column? Say we're doing object classification, then the output could be described as a one-hot encoded vector.

**Comment by Marsmaennchen221** [comment]
> Should the output not be a table instead of a column? Say we're doing object classification, then the output could be described as a one-hot encoded vector.

Yes, you are right, the table should have the same amount of columns as the nn module has as output neurons. In this case the table should only contain numerical columns with values between 0 and 1. For easy use, we could also allow a column that will be one hot encoded in the Dataset.
