### ISSUE TITLE
feat: add to tagged_table/for neural network

### ISSUE THREAD

**Issue by Gerhardsa0** [Safe-DS/Library#618]
### Is your feature request related to a problem?

Right now, the nn interface only allows ```TaggedTable``` as an input. 

For ```TimeSeries``` I will add a temporary solution, with ```to_tagged_table```, which converts the ```TimeSeries``` into a tagged table. This can also be useful for the future implementation of the InputLayer of the nn Interface.

### Desired solution

Right now just a temporary solution and the Integration into the InputLayer Interface.

The lag parameter could also take place here

**Comment by Gerhardsa0** [comment]
This is not a good way to solve the problem, as the windows are not held as data internally and are more used a schema for the data to load into the tensors.

So some deeper changes will be made.

**Comment by lars-reimann** [comment]
Seems related to our discussion about input/output layers that handle the conversion from/to tensor. Also seems related to @Marsmaennchen221's work on a `DataSet` class for images.
