### ISSUE TITLE
Change `TaggedTable._into_dataloader_with_classes` to use `to_numpy()` instead of `values`

### ISSUE THREAD

**Issue by Marsmaennchen221** [Safe-DS/Library#635]
### Is your feature request related to a problem?

Currently, the method uses `DataFrame.values` to convert a pandas `DataFrame` into a PyTorch `Tensor`. It is recommended to use `DataFrame.to_numpy()` instead, as this does the same, but `DataFrame.values` could be deprecated soon. In the documentation from `DataFrame.values` it is also recommended to use `DataFrame.to_numpy` instead.

### Desired solution

Change lines 902 and 911 from `torch.Tensor(self.features._data.values),` to `torch.Tensor(self.features._data.to_numpy),`

**Comment by lars-reimann** [comment]
Polars, which we now use for our tabular containers, also has a direct [DataFrame.to_torch](https://docs.pola.rs/docs/python/dev/reference/dataframe/api/polars.DataFrame.to_torch.html).

**Comment by lars-reimann** [comment]
Has been done as part of #752.
