### ISSUE TITLE
Simplify `TaggedTable`

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/Library#647]
### Is your feature request related to a problem?

We've already spent a lot of time overriding `Table` methods in `TaggedTable` just to keep the tagging. There are also more issues waiting, e.g. https://github.com/Safe-DS/Library/issues/644. Moreover, we also want to connect other types of input and output data, e.g. images to a table, so `TaggedTable` is just a special case of a more abstract `Dataset` concept.

### Desired solution

* Don't inherit `Table` in `TaggedTable`.
* Get rid of all the overridden `Table` methods.
* `Table.tagColumn` can stay. It's now the final step before passing the data to an ML model.
* `Regressor.fit` and `Classifier.fit` could still return a `TaggedTable` or maybe just a `Table`?

**Comment by lars-reimann** [comment]
There's also a strong correlation between `TaggedTable` and the `InputConversionTable`. Both expect names of features and the name of the target.

**Comment by Gerhardsa0** [comment]
> There's also a strong correlation between `TaggedTable` and the `InputConversionTable`. Both expect names of features and the name of the target.

I aggree, also with TimeSeries and `test:inout_conversion_time_series`. Maybe we should let the NN detect the type and then cast, because a lot of information is stored there.
I will make a prototype in my PR #615
