### ISSUE TITLE
Bug: when using plot_compare_time_series

### ISSUE THREAD

**Issue by Gerhardsa0** [Safe-DS/Library#658]
### Describe the bug

When using plot_compare_time_series it doesnt work some times, this is because one column has the name "value", which is used by default from pandas.

### To Reproduce

Create a time series with a target column named value and try to call the function.

### Expected behavior

It should just plot the time series, not dependet of the name

**Comment by lars-reimann** [comment]
Since this method is now removed entirely, I'll close this issue.
