### ISSUE TITLE
Add more data processing steps to the classification tutorial

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/Library#686]
The current [classification tutorial](https://library.safeds.com/en/stable/tutorials/classification/) is missing important steps:

* Remove some columns completely
* Impute `age` and maybe `fare`
* Reverse transform the resulting table.

It should also use headings instead of an ordered list to populate the table of contents. Ideally, it should match the "Getting started" tutorial for the DSL closely, so it's easy to compare DSL and Python syntax.

**Comment by LIEeOoNn** [comment]
with "reverse transform the resulting table" is meant to just reverse the OneHotEncoding, because we imputed missing values with SImpleImputer which isn't invertible

**Comment by lars-reimann** [comment]
> with "reverse transform the resulting table" is meant to just reverse the OneHotEncoding, because we imputed missing values with SImpleImputer which isn't invertible

Correct.
