### ISSUE TITLE
feat: get rid off output and input conversion for user

### ISSUE THREAD

**Issue by Gerhardsa0** [Safe-DS/Library#732]
### Is your feature request related to a problem?

Right now the user needs to set Input and Output conversion, but its always the same type of conversion.

### Desired solution

Create one conversion, which the user sees.

**Comment by lars-reimann** [comment]
Is this different from https://github.com/Safe-DS/Library/issues/656?

**Comment by Gerhardsa0** [comment]
> Is this different from #656?

@Marsmaennchen221 and I were thinking about removing Output and Input Conversion and generalizing it, to a Conversion.
The problem with that is, that for Time Series, I like that I have two separate interfaces for defining parameters, like window_size, forecast_horizon and prediction_name.

**Comment by lars-reimann** [comment]
I'm wondering whether the output conversion is really needed. We should already know from the dataset we get as input what the desired shape of the output is.

**Comment by lars-reimann** [comment]
Superseded by https://github.com/Safe-DS/Library/issues/954.
