### ISSUE TITLE
Add `KNearestNeighborsImputer`

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/Library#743]
### Is your feature request related to a problem?

We currently only have a basic imputer, but there are more sophisticated imputation strategies.

### Desired solution

Add a `KNearestNeighborsImputer` that uses [the KNNImputer of scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.impute.KNNImputer.html) internally.

* Superclass: `TableTransformer`
* Constructor parameters:
  * `neighbor_count: int`,
  * `column_names: str | list[str] | None = None` (keyword-only). List of columns to transform, if None all columns passed in `fit`.
  * `value_to_replace: float | str | None = None` (keyword-only)
* Attributes:
  * `self._wrapped_transformer: sk_KNNImputer | None = None`
* `fit`:
  * Call `_check_columns_exist` to ensure columns to transform exist
  * Raise value error if `row_count` is 0
  * Create a new instance of the `KNearestNeighborsImputer`, don't mutate it in place
  * Create and fit an `sk_KNNImputer` and store it in `_wrapped_transformer` of the copied transformer
* `transform`:
  * `TransformerNotFittedError` if transformer is not fitted
  * Call `_check_columns_exist` to ensure columns to transform exist

  * Transform with the `_wrapped_transformer`

**Comment by LIEeOoNn** [comment]
is this a feat or how should we name the branch ?

**Comment by lars-reimann** [comment]
The branch name is irrelevant. The PR type should be `feat`. See [here](https://github.com/Safe-DS/.github/blob/c8edf5f9243b2ae78d7d5864168a7c65185f0932/.github/CONTRIBUTING.md#types) for a list of PR types.

**Comment by LIEeOoNn** [comment]
i was wondering if we should also check if the `value_toreplace` is in the col or not and raise an error if not or just let the user figure it out

**Comment by LIEeOoNn** [comment]
Do we have to add `KNearestNeighborsImputer` to this[ test_table_transformer.py](https://github.com/Safe-DS/Library/blob/6fbe5379ae7676906bf8d0f21fe00926d792c60f/tests/safeds/data/tabular/transformation/test_table_transformer.py) would make sense,<br> which makes me ask myself if I need to write extra `hash` tests here when I only need to add one line of code at [ test_table_transformer.py](https://github.com/Safe-DS/Library/blob/6fbe5379ae7676906bf8d0f21fe00926d792c60f/tests/safeds/data/tabular/transformation/test_table_transformer.py) 
@lars-reimann

**Comment by lars-reimann** [comment]
> Do we have to add `KNearestNeighborsImputer` to this[ test_table_transformer.py](https://github.com/Safe-DS/Library/blob/6fbe5379ae7676906bf8d0f21fe00926d792c60f/tests/safeds/data/tabular/transformation/test_table_transformer.py) would make sense, which makes me ask myself if I need to write extra `hash` tests here when I only need to add one line of code at [ test_table_transformer.py](https://github.com/Safe-DS/Library/blob/6fbe5379ae7676906bf8d0f21fe00926d792c60f/tests/safeds/data/tabular/transformation/test_table_transformer.py) @lars-reimann

Yep, it's suffices to add the transformer to that file.
