### ISSUE TITLE
convert_to_grayscale not changing the channel to 1 

### ISSUE THREAD

**Issue by LIEeOoNn** [Safe-DS/Library#796]
### Describe the bug

When using convert_to_grayscale the channel attr does not change its value,
only the change_channel meth does correctly 

### To Reproduce

```python 
images, files_names = ImageList.from_files("archive/traffic_Data/smallData", return_filenames=True)
print(images.convert_to_grayscale().channel)
print(images.change_channel(1).channel)
```

```
Output:
3
1
```

### Expected behavior

The channels number should be changed to 1 when using covert_to_grayscale

**Comment by lars-reimann** [comment]
@Marsmaennchen221 Is there a reason we cannot always set `num_output_channels=1` for `func2.rgb_to_grayscale`?

**Comment by Marsmaennchen221** [comment]
@lars-reimann and I discussed that this is the expected behavior. We will include this behavior in the docstrings to make this more clear. See #833
