### ISSUE TITLE
`Cell.first_not_none`

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/Library#799]
### Is your feature request related to a problem?

When transforming a column of a table or computing a new one, it is sometimes beneficial to compute multiple values and pick the first that is not `None`. For example, we might try to transform a column that contains date strings in various formats into an actual date column.

### Desired solution

Add a static method `Cell.first_not_none`. It should have one parameter `cells: list[Cell]` and return a new cell containing the first non-None cell value. The implementation should use the `_LazyCell`.

Use [`pl.coalesce`](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.coalesce.html#polars.coalesce) internally.

Return `None` if all conversions returned `None`.

**Comment by LIEeOoNn** [comment]
we tried for 2h to implement it but <class polars.expr.expr.Expr> apparently can't be wrapped by polars and stopped after trying everything we could think :(

**Comment by lars-reimann** [comment]
Do you have your current code in some branch?

**Comment by LIEeOoNn** [comment]
> Do you have your current code in some branch?

we do at #799

**Comment by lars-reimann** [comment]
I've pushed an implementation of `first_not_none` to `799-cellfirst_not_none`. It still needs documentation (including example usage) and tests, though.
