### ISSUE TITLE
Remove `time_column` from `TimeSeriesDataset`

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/Library#806]
### Is your feature request related to a problem?

The `time_column` is never used for training. Moreover, time series analysis also works without an explicit time column (e.g. one row per day) or with multiple time columns (e.g. hour/minute/second).

### Desired solution

Remove the `time_column` from `TimeSeriesDataset`.

**Comment by Gerhardsa0** [comment]
should this go in #767 or should I wait for review?

**Comment by lars-reimann** [comment]
I won't have time to review #767, unfortunately. So feel free to add this change there and coordinate with @sibre28 or @Marsmaennchen221.
