### ISSUE TITLE
Column.missing_value_count() breaks with mixed data types

### ISSUE THREAD

**Issue by sibre28** [Safe-DS/Library#823]
### Describe the bug

A Column should only count None as missing values. In the case of the column data having mixed Datatypes(ex. int and String) the function sometimes classifies values of anything but one type as missing. It seems to define the type of the first value as the Columntype and reject all other Types.

### To Reproduce

Some Example Cases:

print(Column("test", [1, None, "a"]).missing_value_count())
> 2

print(Column("test", [1, 1, "a"]).missing_value_count())
> 1

print(Column("test", ["a", 1, 1]).missing_value_count())
> 2

print(Column("test", ["A", 1, 0.0, True, None, "A").missing_value_count())
> 4

### Expected behavior

Only count None as a missing value.

**Comment by lars-reimann** [comment]
That is by design: Mixed columns are no longer supported, since we changed the underlying data frame library from pandas to polars, which requires homogeneous data.
