### ISSUE TITLE
Functional table transformer

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/Library#858]
### Is your feature request related to a problem?

Currently, users can transform a table either with a `TableTransformer` or with the methods of `Table`. However, only a `TableTransformer` can be used in a `SequentialTableTransformer` (see #802).

### Desired solution

* Add a new class `FunctionalTableTransformer`
* **Superclass:** `TableTransformer`
* **Constructor parameters:**
  * `transformer: Callable[[Table], Table]` The function transforms a table and returns the transformed table.
* `is_fitted`: Always `True`, immediately after constructing the model.
* `fit`: Is a no-OP. Just return `self`.
* `transform`: Call the `transformer` you got in the constructor and return the result.

**Comment by wastedareas** [comment]
All tests completed successfully
