### ISSUE TITLE
Unreadable labels of correlation heatmap

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/Library#871]
### Describe the bug

The x-labels of a correlation heatmap overlap, which greatly reduces readability. The y-labels are partially cut off.

### To Reproduce

Check the [tutorial for data visualization](https://library.safeds.com/en/latest/tutorials/data_visualization/#correlation-heatmap):

![Untitled](https://github.com/Safe-DS/Library/assets/2501322/37dbbe46-4419-482f-a361-0f772bc042ff)

### Expected behavior

Labels should be readable, e.g. by rotating them 90 degrees and ensuring that the created image is large enough.

**Comment by franzitn** [comment]
Removed the changes and only commitet modified snapshots
